#!/bin/bash
cd ~/tf2server/steamcmd_linux/csgo

cd game/bin/linuxsteamrt64
./cs2 -dedicated

exit
# Below is old CS:GO launch system
export HOME=/tmp # Break $HOME so it can't find ~/.steam/sdk32/steamclient.so and thus won't get confuzzled by the Steam GUI
export LD_LIBRARY_PATH=bin
ARGS="./srcds_linux -console -game csgo -usercon -authkey $STEAM_API_KEY +sv_setsteamaccount $STEAM_CSGO_GSLT +sv_tags drzed"
case $1 in
  guardian_*)
    fn=$1
    map=${fn#guardian_}
    map=${map%.cfg}
    map=${map%_alt[0-9]}
    : TODO: Search the workshop for any map that isn't found, and
    : offer a host_workshop_map command to fetch it. Steam ID
    : 76561198082857351 is the CS:GO Official account. Once it's
    : been downloaded once, this code will all work.
    : TODO: Also support newer missions, which don't have their
    : map file names in the config file name. But they don't need
    : any cvar translation, so it is a bit easier.
    weap=`awk '/mp_guardian_special_weapon_needed/{print $NF}' csgo/maps/cfg/$fn|tr -d '\r'`
    case $weap in
      "") echo Old guardian missions with blank weapon may not work ;;
      any) weap='""' ;;
      *) weap='"%weapon_'$weap'%"' ;;
    esac
    echo "
	execwithwhitelist $fn */maps
	bot_quota 5
	bot_quota_mode normal
	mp_guardian_special_weapon_needed $weap
    " >csgo/cfg/oldguardian.cfg
    $ARGS +game_type 4 +game_mode 0 +map $map
  ;;
  *)
$ARGS +exec server_last
esac
