#!/bin/bash
cd ~/tf2server/steamcmd_linux/satisfactory
export HOME=/tmp # May or may not be necessary, probably doesn't hurt (see csrun)
export LD_LIBRARY_PATH=linux64
./Engine/Binaries/Linux/UE4Server-Linux-Shipping FactoryGame -NOSTEAM
